API_KEY = '2QZYQ6W3K4TKKUBG'
ENDPOINT_SCHEMA_URL  = 'https://psrc-q8qx7.us-central1.gcp.confluent.cloud'
API_SECRET_KEY = 'vgJqRAVfWDMmwWI5gjEscND6/50cxKRqkJM8hcVRu0gSIev5hr+GLpG7V25rZJIX'
BOOTSTRAP_SERVER = 'pkc-12576z.us-west2.gcp.confluent.cloud:9092'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'LW3MCWYKAN46TDGV'
SCHEMA_REGISTRY_API_SECRET = 'quN6GFwuc5/88KSOoAZKt4RsL5BxbI1Lo1JtiqCI/94XouBZSYHocBpyxvPiWuKC'


def config_values():
	return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET